apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-risk-scorecard-api
spec:
  type: PublicApi
  lifecycle: production
  owner: rosene
  system: backstage-plugin-risk-scorecard