version: 2
updates:
  # Maintain dependencies for Gradle
  - package-ecosystem: "gradle"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/"
    schedule:
      interval: "weekly"
  # Maintain docker images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
