version: 2
registries:
  dhi:
    type: docker-registry
    url: https://dhi.io
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}
updates:
  # Maintain dependencies for Gradle
  - package-ecosystem: "gradle"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      all-gradle-dependencies:
        patterns:
          - "*"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
  # Maintain docker images
  - package-ecosystem: "docker"
    directory: "/"
    registries:
      - dhi
    schedule:
      interval: "daily"
    groups:
      all-docker-dependencies:
        patterns:
          - "*"
