# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "backstage-plugin-risk-scorecard-backend"
  tags:
  - "internal"
spec:
  type: "service"
  lifecycle: "production"
  owner: "skvis"
  system: "ros-as-code"
  providesApis:
  - "backstage-plugin-risk-scorecard-backend-api"
---
apiVersion: "backstage.io/v1alpha1"
kind: "API"
metadata:
  name: "backstage-plugin-risk-scorecard-backend-api"
  tags:
  - "internal"
spec:
  type: "openapi"
  lifecycle: "production"
  owner: "skvis"
  definition: |
    openapi: "3.0.0"
    info:
        title: backstage-plugin-risk-scorecard-backend API
    paths:
