services:
  skip:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ISSUER_URI=${ISSUER_URI}
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_INSTALLATION_ID=${GITHUB_INSTALLATION_ID}
      - GITHUB_PRIVATE_KEY_SECRET_NAME=${GITHUB_PRIVATE_KEY_SECRET_NAME}
      - RISC_FOLDER_PATH=${RISC_FOLDER_PATH}
      - JSON_SCHEMA_PATH=${JSON_SCHEMA_PATH}
      - ENTRA_ID_TENANT_ID=${ENTRA_ID_TENANT_ID}
      - FILENAME_PREFIX=${FILENAME_PREFIX}
      - FILENAME_POSTFIX=${FILENAME_POSTFIX}
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/code
