services:
  local:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/code
    env_file:
      - .env
  skip:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ISSUER_URI=${ISSUER_URI}
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_INSTALLATION_ID=${GITHUB_INSTALLATION_ID}
      - GITHUB_PRIVATE_KEY_BASE64_ENCODED=${GITHUB_PRIVATE_KEY_BASE64_ENCODED}
      - RISC_FOLDER_PATH=${RISC_FOLDER_PATH}
      - JSON_SCHEMA_BASE_URL=${JSON_SCHEMA_BASE_URL}
      - FILENAME_PREFIX=${FILENAME_PREFIX}
      - FILENAME_POSTFIX=${FILENAME_POSTFIX}
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/code
