services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - LOCAL=true
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env

  appm4:
    # This app is made for Mac M4.
    # Conditionals are difficult in Dockerfiles, we therefore opted for a separate setup
    # for M4 architecture until the original image has patched whatever caused issues.
    build:
      context: .
      dockerfile: Dockerfile.M4
      args:
        - LOCAL=true
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env

  skip:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ISSUER_URI=${ISSUER_URI}
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_INSTALLATION_ID=${GITHUB_INSTALLATION_ID}
      - GITHUB_PRIVATE_KEY_BASE64_ENCODED=${GITHUB_PRIVATE_KEY_BASE64_ENCODED}
      - RISC_FOLDER_PATH=${RISC_FOLDER_PATH}
      - FILENAME_PREFIX=${FILENAME_PREFIX}
      - FILENAME_POSTFIX=${FILENAME_POSTFIX}
    ports:
      - "8080:8080"
      - "8081:8081"
