services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LOCAL: true
        BUILD_IMAGE: ${BUILD_IMAGE:-eclipse-temurin:23-jre-alpine}
        IMAGE: ${IMAGE:-eclipse-temurin:23-alpine}
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env

  skip:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ISSUER_URI=${ISSUER_URI}
      - GITHUB_APP_ID=${GITHUB_APP_ID}
      - GITHUB_INSTALLATION_ID=${GITHUB_INSTALLATION_ID}
      - GITHUB_PRIVATE_KEY_BASE64_ENCODED=${GITHUB_PRIVATE_KEY_BASE64_ENCODED}
      - RISC_FOLDER_PATH=${RISC_FOLDER_PATH}
      - FILENAME_PREFIX=${FILENAME_PREFIX}
      - FILENAME_POSTFIX=${FILENAME_POSTFIX}
    ports:
      - "8080:8080"
      - "8081:8081"