services:
  cache:
    image: redis:alpine
    restart: always
    container_name: "ros-backend-redis"
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local