services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_IMAGE: ${BUILD_IMAGE:-eclipse-temurin:25-jre-alpine}
        SOPS_BUILD_IMAGE: golang:1.25.7
        SOPS_VERSION_ARG: 3.11.0
        DISTROLESS_IMAGE: ${DISTROLESS_IMAGE:-gcr.io/distroless/java25-debian13}
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - LOCAL=true
    env_file:
      - .env