creation_rules:
  - path_regex: \.ros\.yaml$
    shamir_threshold: 2
    key_groups:
      - age:
          - 'age1ayuv56c98uukut752jpxl68tpch2yjvx5z3agk0t73h79kq3z4fstrtvqf'
      - gcp_kms:
          - resource_id: projects/spire-ros-5lmr/locations/eur4/keyRings/ROS/cryptoKeys/ros-as-code
