apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: kv-ros-backend
spec:
  type: service
  owner: rosene
  system: kv-ros
  lifecycle: production
  targets:
    - .backstage/system/system.yaml
    - .backstage/component/ros.yaml
    - .backstage/component/publicApi.yaml
